cfg = {
    "prog": "fwew",
    "trigger": "!fwew",
    "name": "fwew-discord",
    "ver_num": "1.1.0",
    "ver_chn": "dev",
    "ver_cod": "\"Letwana Nantang\"",
    "space": " ",
    "dbl_quote": '"',
    "sngl_quote": "'",
    "md_codeblock": "```",
    "squote_chars": "‘’`´",
    "quote_chars": "„“”«»",
    "default_flags": "-ipa -m",
    "bad_chars": "`~@#$%^&*(){}<>_/;:!?|+\\",
    "token": "placeDiscordBotTokenHere",
}
